import { c as createAstro, d as createComponent, r as renderComponent, e as renderTemplate, m as maybeRenderHead, f as addAttribute, u as unescapeHTML } from '../chunks/astro/server_Ba64zHfB.mjs';
import 'kleur/colors';
import { $ as $$Icon, a as $$Ident, b as $$Head } from '../chunks/Icon_B8z5UiVG.mjs';
/* empty css                                 */
import { d as datasetObj, g as groupOrders, m as memes } from '../chunks/dataset_C3x4c14j.mjs';
import { s as submissionFormUrl } from '../chunks/config_Bj2EZlPB.mjs';
import 'clsx';
import { t as templateTypeGlossary, p as peopleGlossary, c as contentTypeGlossary } from '../chunks/glossary_zZwnW_CE.mjs';
/* empty css                                  */
export { renderers } from '../renderers.mjs';

/** @returns {void} */

function run(fn) {
	return fn();
}

function blank_object() {
	return Object.create(null);
}

/**
 * @param {Function[]} fns
 * @returns {void}
 */
function run_all(fns) {
	fns.forEach(run);
}

function null_to_empty(value) {
	return value == null ? '' : value;
}

let current_component;

/** @returns {void} */
function set_current_component(component) {
	current_component = component;
}

// general each functions:

function ensure_array_like(array_like_or_iterator) {
	return array_like_or_iterator?.length !== undefined
		? array_like_or_iterator
		: Array.from(array_like_or_iterator);
}

const ATTR_REGEX = /[&"<]/g;
const CONTENT_REGEX = /[&<]/g;

/**
 * Note: this method is performance sensitive and has been optimized
 * https://github.com/sveltejs/svelte/pull/5701
 * @param {unknown} value
 * @returns {string}
 */
function escape(value, is_attr = false) {
	const str = String(value);
	const pattern = is_attr ? ATTR_REGEX : CONTENT_REGEX;
	pattern.lastIndex = 0;
	let escaped = '';
	let last = 0;
	while (pattern.test(str)) {
		const i = pattern.lastIndex - 1;
		const ch = str[i];
		escaped += str.substring(last, i) + (ch === '&' ? '&amp;' : ch === '"' ? '&quot;' : '&lt;');
		last = i + 1;
	}
	return escaped + str.substring(last);
}

/** @returns {string} */
function each(items, fn) {
	items = ensure_array_like(items);
	let str = '';
	for (let i = 0; i < items.length; i += 1) {
		str += fn(items[i], i);
	}
	return str;
}

let on_destroy;

/** @returns {{ render: (props?: {}, { $$slots, context }?: { $$slots?: {}; context?: Map<any, any>; }) => { html: any; css: { code: string; map: any; }; head: string; }; $$render: (result: any, props: any, bindings: any, slots: any, context: any) => any; }} */
function create_ssr_component(fn) {
	function $$render(result, props, bindings, slots, context) {
		const parent_component = current_component;
		const $$ = {
			on_destroy,
			context: new Map(context || (parent_component ? parent_component.$$.context : [])),
			// these will be immediately discarded
			on_mount: [],
			before_update: [],
			after_update: [],
			callbacks: blank_object()
		};
		set_current_component({ $$ });
		const html = fn(result, props, bindings, slots);
		set_current_component(parent_component);
		return html;
	}
	return {
		render: (props = {}, { $$slots = {}, context = new Map() } = {}) => {
			on_destroy = [];
			const result = { title: '', head: '', css: new Set() };
			const html = $$render(result, props, {}, $$slots, context);
			run_all(on_destroy);
			return {
				html,
				css: {
					code: Array.from(result.css)
						.map((css) => css.code)
						.join('\n'),
					map: null // TODO
				},
				head: result.title + result.head
			};
		},
		$$render
	};
}

/** @returns {string} */
function add_attribute(name, value, boolean) {
	if (value == null || (boolean)) return '';
	const assignment = `="${escape(value, true)}"`;
	return ` ${name}${assignment}`;
}

/* src/components/CheckboxMultiSelect.svelte generated by Svelte v4.2.20 */

const css = {
	code: ".container.svelte-1wz6l0l{background-color:#555;border-radius:4px;position:relative}.container.svelte-1wz6l0l:focus-visible{outline:none}.container.svelte-1wz6l0l:after{border-left:5px solid transparent;border-right:5px solid transparent;border-top:5px solid currentColor;content:\"\";height:0;margin-top:-2px;pointer-events:none;position:absolute;right:8px;top:50%;width:0}.dropdown.svelte-1wz6l0l{background-color:inherit;border:1px solid white;border-radius:4px;display:none;flex-direction:column;max-height:90vh;overflow-y:auto;padding:0.5em 0.5em 1em;position:absolute;width:max-content;z-index:9;min-width:calc(100% + 3px);max-width:calc(100vw - 4px)}.dropdown.open.svelte-1wz6l0l{display:flex}span.input.svelte-1wz6l0l{border-radius:4px;cursor:pointer;display:inline-block;height:100%;line-height:calc(2.25em - 4px);overflow:hidden;padding:5px 11px;text-overflow:ellipsis;white-space:nowrap;width:100%}span.input.svelte-1wz6l0l:focus-visible{outline:1px solid white}span.input[contenteditable=\"true\"].svelte-1wz6l0l:empty:before{content:attr(placeholder);opacity:0.5;pointer-events:none}span.input.show-indicator.svelte-1wz6l0l{padding:5px 75px 5px 11px}span.input.show-indicator.svelte-1wz6l0l::after{background-color:var(--primary-accent);border-radius:8px;content:attr(data-selected);display:block;line-height:25px;padding:0 6px;position:absolute;right:48px;top:7px}button.svelte-1wz6l0l{color:white;font-size:25px;padding:0 4px;position:absolute;right:20px;top:50%;transform:translateY(-50%)}label.group.svelte-1wz6l0l{font-size:1.1em;font-weight:bold;margin:1em 0 0.5em}label.suboption.svelte-1wz6l0l{margin-left:10px;padding-left:3em;text-indent:-3em}",
	map: "{\"version\":3,\"file\":\"CheckboxMultiSelect.svelte\",\"sources\":[\"CheckboxMultiSelect.svelte\"],\"sourcesContent\":[\"<svelte:options accessors />\\n\\n<script>\\n  import { tick } from \\\"svelte\\\";\\n  import { computePosition, shift } from \\\"@floating-ui/dom\\\";\\n\\n  export let options;\\n  export let selectId;\\n  export let containerClass = undefined;\\n  export let title = undefined;\\n  export let placeHolder = \\\"Select an item...\\\";\\n\\n  let filteredOptions;\\n  let selectedValues = [];\\n  let open = false;\\n  let dropdown;\\n  let input;\\n  let selectEl;\\n  let hasGroups = !Array.isArray(options);\\n\\n  const resetFilteredOptions = () => {\\n    if (hasGroups) {\\n      filteredOptions = Object.values(options)\\n        .map((group) => group.options)\\n        .flat();\\n    } else {\\n      filteredOptions = options;\\n    }\\n  };\\n\\n  const positionDropdown = () => {\\n    computePosition(input, dropdown, {\\n      placement: \\\"bottom-start\\\",\\n      middleware: [shift({ padding: 2 })],\\n    }).then(({ x, y }) => {\\n      const inputTop = input.getBoundingClientRect().top;\\n      Object.assign(dropdown.style, {\\n        left: `${x}px`,\\n        top: `${y + 6}px`,\\n        maxHeight: `calc(100vh - ${inputTop + y + 10}px)`,\\n      });\\n    });\\n  };\\n\\n  const activateDropdown = async () => {\\n    if (open) return;\\n    resetFilteredOptions();\\n    open = true;\\n    positionDropdown();\\n    await tick();\\n    input.innerHTML = \\\"\\\";\\n    input.focus();\\n  };\\n\\n  const closeDropdown = () => {\\n    open = false;\\n    input.innerHTML = selectedValues.length\\n      ? selectedValues.join(\\\" | \\\")\\n      : placeHolder;\\n    input.blur();\\n  };\\n\\n  const toggleDropdown = () => (open ? closeDropdown() : activateDropdown());\\n\\n  const search = async () => {\\n    open = true;\\n    resetFilteredOptions();\\n\\n    if (!input.innerHTML) return;\\n\\n    if (input.innerText) {\\n      const searchParts = input.innerText.toLowerCase().split(\\\" \\\");\\n\\n      filteredOptions = filteredOptions.filter((option) =>\\n        searchParts.every((searchPart) =>\\n          option.label.toLowerCase().includes(searchPart),\\n        ),\\n      );\\n    }\\n  };\\n\\n  const selectedValuesUpdated = async () => {\\n    input.focus();\\n    await tick();\\n    selectEl.dispatchEvent(\\n      new CustomEvent(\\\"updated\\\", {\\n        bubbles: false,\\n        detail: selectedValues,\\n      }),\\n    );\\n  };\\n</script>\\n\\n<div\\n  {title}\\n  id={selectId}\\n  bind:this={selectEl}\\n  class={`container ${containerClass || \\\"\\\"}`}\\n  on:clear={() => {\\n    selectedValues = [];\\n    closeDropdown();\\n  }}\\n>\\n  <span\\n    class=\\\"input\\\"\\n    spellcheck=\\\"false\\\"\\n    contenteditable=\\\"true\\\"\\n    placeholder=\\\"Type to filter...\\\"\\n    data-selected={selectedValues.length}\\n    class:show-indicator={selectedValues.length}\\n    bind:this={input}\\n    on:input={search}\\n    on:focus={activateDropdown}\\n    on:mousedown|preventDefault={toggleDropdown}>{@html placeHolder}</span\\n  >\\n  {#if selectedValues.length}\\n    <button\\n      on:click={() => {\\n        selectedValues = [];\\n        selectedValuesUpdated();\\n      }}>×</button\\n    >\\n  {/if}\\n\\n  <div class=\\\"dropdown\\\" class:open bind:this={dropdown}>\\n    {#if hasGroups}\\n      {#each Object.keys(options).filter((group) => options[group].options) as group}\\n        {@const subOptions = options[group].options}\\n        {@const optionValues = subOptions.map((o) => o.value)}\\n        <label class=\\\"group\\\">\\n          <input\\n            type=\\\"checkbox\\\"\\n            checked={optionValues.every((option) =>\\n              selectedValues.includes(option),\\n            )}\\n            indeterminate={optionValues.some((option) =>\\n              selectedValues.includes(option),\\n            ) &&\\n              !optionValues.every((option) => selectedValues.includes(option))}\\n            on:change={({ target }) => {\\n              if (target.checked) {\\n                // select all options for this group\\n                selectedValues = [\\n                  ...new Set([...selectedValues, ...optionValues]),\\n                ];\\n              } else {\\n                // unselect all options for this group\\n                selectedValues = selectedValues.filter(\\n                  (option) => !optionValues.includes(option),\\n                );\\n              }\\n              selectedValuesUpdated();\\n            }}\\n          />\\n          {group} [{options[group].count}]\\n        </label>\\n        {#each subOptions as option}\\n          {#if filteredOptions?.includes(option)}\\n            <label class=\\\"suboption\\\">\\n              <input\\n                type=\\\"checkbox\\\"\\n                value={option.value}\\n                bind:group={selectedValues}\\n                on:change={selectedValuesUpdated}\\n              />\\n              {option.label}\\n            </label>\\n          {/if}\\n        {/each}\\n      {/each}\\n    {:else}\\n      {#each options as option}\\n        {#if filteredOptions?.includes(option)}\\n          <label>\\n            <input\\n              type=\\\"checkbox\\\"\\n              value={option.value}\\n              bind:group={selectedValues}\\n              on:change={selectedValuesUpdated}\\n            />\\n            {option.label}\\n          </label>\\n        {/if}\\n      {/each}\\n    {/if}\\n    {#if !filteredOptions?.length}\\n      <span>No matching options</span>\\n    {/if}\\n  </div>\\n</div>\\n\\n<svelte:window\\n  on:click={({ target }) => {\\n    if (open && !(dropdown.contains(target) || input.contains(target))) {\\n      closeDropdown();\\n    }\\n  }}\\n  on:keydown|stopPropagation={({ key }) => {\\n    if (open && key === \\\"Escape\\\") closeDropdown();\\n  }}\\n/>\\n\\n<style lang=\\\"postcss\\\">\\n  .container {\\n    background-color: #555;\\n    border-radius: 4px;\\n    position: relative;\\n  }\\n\\n    .container:focus-visible {\\n      outline: none;\\n    }\\n\\n    .container:after {\\n      border-left: 5px solid transparent;\\n      border-right: 5px solid transparent;\\n      border-top: 5px solid currentColor;\\n      content: \\\"\\\";\\n      height: 0;\\n      margin-top: -2px;\\n      pointer-events: none;\\n      position: absolute;\\n      right: 8px;\\n      top: 50%;\\n      width: 0;\\n    }\\n\\n  .dropdown {\\n    background-color: inherit;\\n    border: 1px solid white;\\n    border-radius: 4px;\\n    display: none;\\n    flex-direction: column;\\n    max-height: 90vh;\\n    overflow-y: auto;\\n    padding: 0.5em 0.5em 1em;\\n    position: absolute;\\n    width: max-content;\\n    z-index: 9;\\n\\n    min-width: calc(100% + 3px);\\n    max-width: calc(100vw - 4px);\\n  }\\n\\n  .dropdown.open {\\n      display: flex;\\n    }\\n\\n  span.input {\\n    border-radius: 4px;\\n    cursor: pointer;\\n    display: inline-block;\\n    height: 100%;\\n    line-height: calc(2.25em - 4px);\\n    overflow: hidden;\\n    padding: 5px 11px;\\n    text-overflow: ellipsis;\\n    white-space: nowrap;\\n    width: 100%;\\n  }\\n\\n  span.input:focus-visible {\\n      outline: 1px solid white;\\n    }\\n\\n  span.input[contenteditable=\\\"true\\\"]:empty:before {\\n      content: attr(placeholder);\\n      opacity: 0.5;\\n      pointer-events: none;\\n    }\\n\\n  span.input.show-indicator {\\n      padding: 5px 75px 5px 11px;\\n    }\\n\\n  span.input.show-indicator::after {\\n        background-color: var(--primary-accent);\\n        border-radius: 8px;\\n        content: attr(data-selected);\\n        display: block;\\n        line-height: 25px;\\n        padding: 0 6px;\\n        position: absolute;\\n        right: 48px;\\n        top: 7px;\\n      }\\n\\n  button {\\n    color: white;\\n    font-size: 25px;\\n    padding: 0 4px;\\n    position: absolute;\\n    right: 20px;\\n    top: 50%;\\n    transform: translateY(-50%);\\n  }\\n\\n  label.group {\\n      font-size: 1.1em;\\n      font-weight: bold;\\n      margin: 1em 0 0.5em;\\n    }\\n\\n  label.suboption {\\n      margin-left: 10px;\\n      padding-left: 3em;\\n      text-indent: -3em;\\n    }\\n</style>\\n\"],\"names\":[],\"mappings\":\"AA2ME,yBAAW,CACT,gBAAgB,CAAE,IAAI,CACtB,aAAa,CAAE,GAAG,CAClB,QAAQ,CAAE,QACZ,CAEE,yBAAU,cAAe,CACvB,OAAO,CAAE,IACX,CAEA,yBAAU,MAAO,CACf,WAAW,CAAE,GAAG,CAAC,KAAK,CAAC,WAAW,CAClC,YAAY,CAAE,GAAG,CAAC,KAAK,CAAC,WAAW,CACnC,UAAU,CAAE,GAAG,CAAC,KAAK,CAAC,YAAY,CAClC,OAAO,CAAE,EAAE,CACX,MAAM,CAAE,CAAC,CACT,UAAU,CAAE,IAAI,CAChB,cAAc,CAAE,IAAI,CACpB,QAAQ,CAAE,QAAQ,CAClB,KAAK,CAAE,GAAG,CACV,GAAG,CAAE,GAAG,CACR,KAAK,CAAE,CACT,CAEF,wBAAU,CACR,gBAAgB,CAAE,OAAO,CACzB,MAAM,CAAE,GAAG,CAAC,KAAK,CAAC,KAAK,CACvB,aAAa,CAAE,GAAG,CAClB,OAAO,CAAE,IAAI,CACb,cAAc,CAAE,MAAM,CACtB,UAAU,CAAE,IAAI,CAChB,UAAU,CAAE,IAAI,CAChB,OAAO,CAAE,KAAK,CAAC,KAAK,CAAC,GAAG,CACxB,QAAQ,CAAE,QAAQ,CAClB,KAAK,CAAE,WAAW,CAClB,OAAO,CAAE,CAAC,CAEV,SAAS,CAAE,KAAK,IAAI,CAAC,CAAC,CAAC,GAAG,CAAC,CAC3B,SAAS,CAAE,KAAK,KAAK,CAAC,CAAC,CAAC,GAAG,CAC7B,CAEA,SAAS,oBAAM,CACX,OAAO,CAAE,IACX,CAEF,IAAI,qBAAO,CACT,aAAa,CAAE,GAAG,CAClB,MAAM,CAAE,OAAO,CACf,OAAO,CAAE,YAAY,CACrB,MAAM,CAAE,IAAI,CACZ,WAAW,CAAE,KAAK,MAAM,CAAC,CAAC,CAAC,GAAG,CAAC,CAC/B,QAAQ,CAAE,MAAM,CAChB,OAAO,CAAE,GAAG,CAAC,IAAI,CACjB,aAAa,CAAE,QAAQ,CACvB,WAAW,CAAE,MAAM,CACnB,KAAK,CAAE,IACT,CAEA,IAAI,qBAAM,cAAe,CACrB,OAAO,CAAE,GAAG,CAAC,KAAK,CAAC,KACrB,CAEF,IAAI,MAAM,CAAC,eAAe,CAAC,MAAM,gBAAC,MAAM,OAAQ,CAC5C,OAAO,CAAE,KAAK,WAAW,CAAC,CAC1B,OAAO,CAAE,GAAG,CACZ,cAAc,CAAE,IAClB,CAEF,IAAI,MAAM,8BAAgB,CACtB,OAAO,CAAE,GAAG,CAAC,IAAI,CAAC,GAAG,CAAC,IACxB,CAEF,IAAI,MAAM,8BAAe,OAAQ,CAC3B,gBAAgB,CAAE,IAAI,gBAAgB,CAAC,CACvC,aAAa,CAAE,GAAG,CAClB,OAAO,CAAE,KAAK,aAAa,CAAC,CAC5B,OAAO,CAAE,KAAK,CACd,WAAW,CAAE,IAAI,CACjB,OAAO,CAAE,CAAC,CAAC,GAAG,CACd,QAAQ,CAAE,QAAQ,CAClB,KAAK,CAAE,IAAI,CACX,GAAG,CAAE,GACP,CAEJ,qBAAO,CACL,KAAK,CAAE,KAAK,CACZ,SAAS,CAAE,IAAI,CACf,OAAO,CAAE,CAAC,CAAC,GAAG,CACd,QAAQ,CAAE,QAAQ,CAClB,KAAK,CAAE,IAAI,CACX,GAAG,CAAE,GAAG,CACR,SAAS,CAAE,WAAW,IAAI,CAC5B,CAEA,KAAK,qBAAO,CACR,SAAS,CAAE,KAAK,CAChB,WAAW,CAAE,IAAI,CACjB,MAAM,CAAE,GAAG,CAAC,CAAC,CAAC,KAChB,CAEF,KAAK,yBAAW,CACZ,WAAW,CAAE,IAAI,CACjB,YAAY,CAAE,GAAG,CACjB,WAAW,CAAE,IACf\"}"
};

const CheckboxMultiSelect = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { options } = $$props;
	let { selectId } = $$props;
	let { containerClass = undefined } = $$props;
	let { title = undefined } = $$props;
	let { placeHolder = "Select an item..." } = $$props;
	let selectedValues = [];
	let dropdown;
	let input;
	let selectEl;
	let hasGroups = !Array.isArray(options);

	if ($$props.options === void 0 && $$bindings.options && options !== void 0) $$bindings.options(options);
	if ($$props.selectId === void 0 && $$bindings.selectId && selectId !== void 0) $$bindings.selectId(selectId);
	if ($$props.containerClass === void 0 && $$bindings.containerClass && containerClass !== void 0) $$bindings.containerClass(containerClass);
	if ($$props.title === void 0 && $$bindings.title && title !== void 0) $$bindings.title(title);
	if ($$props.placeHolder === void 0 && $$bindings.placeHolder && placeHolder !== void 0) $$bindings.placeHolder(placeHolder);
	$$result.css.add(css);

	return `  <div${add_attribute("title", title, 0)}${add_attribute("id", selectId, 0)} class="${escape(null_to_empty(`container ${containerClass || ""}`), true) + " svelte-1wz6l0l"}"${add_attribute("this", selectEl, 0)}><span class="${["input svelte-1wz6l0l", selectedValues.length ? "show-indicator" : ""].join(' ').trim()}" spellcheck="false" contenteditable="true" placeholder="Type to filter..."${add_attribute("data-selected", selectedValues.length, 0)}${add_attribute("this", input, 0)}><!-- HTML_TAG_START -->${placeHolder}<!-- HTML_TAG_END --></span> ${selectedValues.length
	? `<button class="svelte-1wz6l0l" data-svelte-h="svelte-2shgw">×</button>`
	: ``} <div class="${["dropdown svelte-1wz6l0l", ""].join(' ').trim()}"${add_attribute("this", dropdown, 0)}>${hasGroups
	? `${each(Object.keys(options).filter(group => options[group].options), group => {
			let subOptions = options[group].options,
				optionValues = subOptions.map(o => o.value);

			return `  <label class="group svelte-1wz6l0l"><input type="checkbox" ${optionValues.every(option => selectedValues.includes(option))
			? "checked"
			: ""}${add_attribute("indeterminate", optionValues.some(option => selectedValues.includes(option)) && !optionValues.every(option => selectedValues.includes(option)), 0)}> ${escape(group)} [${escape(options[group].count)}]</label> ${each(subOptions, option => {
				return `${``}`;
			})}`;
		})}`
	: `${each(options, option => {
			return `${``}`;
		})}`} ${`<span data-svelte-h="svelte-1ixkdeu">No matching options</span>`
	}</div></div> `;
});

const $$Astro = createAstro("https://memes.sucho.org/");
const $$Filter = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Filter;
  const { title, selectId, placeHolder, containerClass, facet } = Astro2.props;
  const memes$1 = memes;
  const groupOrders$1 = groupOrders;
  const facetValues = datasetObj[facet];
  let options;
  const makeLabels = ({ value, count }) => ({
    value,
    label: `${value} [${count}]`
  });
  if (facetValues[0].group) {
    const groupsHash = groupOrders$1[facet].reduce(
      (acc, group) => ({ ...acc, [group]: [] }),
      {}
    );
    options = facetValues.reduce((hash, obj) => {
      const options2 = (hash[obj.group]?.options || []).concat(makeLabels(obj));
      const count = memes$1.filter(
        (meme) => meme[facet].some((mt) => options2.map((o) => o.value).includes(mt))
      ).length;
      return {
        ...hash,
        [obj.group]: { options: options2, count }
      };
    }, groupsHash);
  } else {
    options = facetValues.map(makeLabels);
  }
  return renderTemplate`${renderComponent($$result, "CheckboxMultiSelect", CheckboxMultiSelect, { "options": options, "selectId": selectId, "containerClass": containerClass, "title": title, "placeHolder": placeHolder, "client:idle": true, "client:component-hydration": "idle", "client:component-path": "/home/runner/work/meme-wall/meme-wall/src/components/CheckboxMultiSelect.svelte", "client:component-export": "default" })}`;
}, "/home/runner/work/meme-wall/meme-wall/src/components/Filter.astro", void 0);

const $$ExtendedFilters = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<div class="more-filters" data-astro-cid-mfzukpfk> ${renderComponent($$result, "Filter", $$Filter, { "title": "Filter by Person", "selectId": "person", "placeHolder": "-- Person --", "facet": "people", "containerClass": "filter", "data-astro-cid-mfzukpfk": true })} ${renderComponent($$result, "Filter", $$Filter, { "title": "Filter by Language", "selectId": "language", "placeHolder": "-- Language --", "facet": "languages", "containerClass": "filter", "data-astro-cid-mfzukpfk": true })} ${renderComponent($$result, "Filter", $$Filter, { "title": "Filter by Country", "selectId": "country", "placeHolder": "-- Country --", "facet": "countries", "containerClass": "filter", "data-astro-cid-mfzukpfk": true })} ${renderComponent($$result, "Filter", $$Filter, { "title": "Filter by Template Type", "selectId": "templateType", "placeHolder": "-- Template Type --", "facet": "templateTypes", "containerClass": "filter", "data-astro-cid-mfzukpfk": true })} </div> `;
}, "/home/runner/work/meme-wall/meme-wall/src/components/ExtendedFilters.astro", void 0);

const $$MainControls = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<div class="controls" data-astro-cid-ti4gnb4m> <div class="count" data-astro-cid-ti4gnb4m> <span data-astro-cid-ti4gnb4m>${memes.length} / ${memes.length}</span> <button class="reset-wall" title="Reset Wall" data-astro-cid-ti4gnb4m>${renderComponent($$result, "Icon", $$Icon, { "name": "reset", "data-astro-cid-ti4gnb4m": true })}</button> </div> ${renderComponent($$result, "Filter", $$Filter, { "title": "Filter Memes", "selectId": "memeType", "placeHolder": "-- Filter by Content --", "facet": "memeTypes", "containerClass": "filter", "data-astro-cid-ti4gnb4m": true })} <div class="search" data-astro-cid-ti4gnb4m> <button class="search" title="Search Memes" data-astro-cid-ti4gnb4m>${renderComponent($$result, "Icon", $$Icon, { "name": "search", "data-astro-cid-ti4gnb4m": true })}</button> <input id="search-input" type="text" data-astro-cid-ti4gnb4m> <label for="search-input" class="visually-hidden" data-astro-cid-ti4gnb4m>Search Term</label> </div> <button class="show-filters" title="Show Filters" data-astro-cid-ti4gnb4m>${renderComponent($$result, "Icon", $$Icon, { "name": "filter", "data-astro-cid-ti4gnb4m": true })} </button> <a class="button" title="Submit a Meme"${addAttribute(submissionFormUrl, "href")} data-astro-cid-ti4gnb4m> ${renderComponent($$result, "Icon", $$Icon, { "name": "upload", "data-astro-cid-ti4gnb4m": true })} </a> <a class="button" title="About"${addAttribute("/about/", "href")} data-astro-cid-ti4gnb4m> ${renderComponent($$result, "Icon", $$Icon, { "name": "info-circle", "data-astro-cid-ti4gnb4m": true })} </a> </div> `;
}, "/home/runner/work/meme-wall/meme-wall/src/components/MainControls.astro", void 0);

const $$OverlayButtons = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<div id="overlay-buttons" data-astro-cid-voj25cpq> <a href="#" class="overlay-button" aria-label="Previous" data-astro-cid-voj25cpq> ${renderComponent($$result, "Icon", $$Icon, { "name": "arrow-narrow-left", "data-astro-cid-voj25cpq": true })} </a> <a href="#" class="overlay-button" aria-label="Next" data-astro-cid-voj25cpq> ${renderComponent($$result, "Icon", $$Icon, { "name": "arrow-narrow-right", "data-astro-cid-voj25cpq": true })} </a> <a href="#" class="overlay-button" aria-label="Close" data-astro-cid-voj25cpq> ${renderComponent($$result, "Icon", $$Icon, { "name": "x", "data-astro-cid-voj25cpq": true })} </a> <a href="#" class="overlay-button" aria-label="Share" data-astro-cid-voj25cpq> ${renderComponent($$result, "Icon", $$Icon, { "name": "share", "data-astro-cid-voj25cpq": true })} </a> </div>  `;
}, "/home/runner/work/meme-wall/meme-wall/src/components/OverlayButtons.astro", void 0);

const $$Header = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<header data-astro-cid-3ef6ksr2> ${renderComponent($$result, "Ident", $$Ident, { "data-astro-cid-3ef6ksr2": true })} ${renderComponent($$result, "MainControls", $$MainControls, { "data-astro-cid-3ef6ksr2": true })} ${renderComponent($$result, "ExtendedFilters", $$ExtendedFilters, { "data-astro-cid-3ef6ksr2": true })} ${renderComponent($$result, "OverlayButtons", $$OverlayButtons, { "data-astro-cid-3ef6ksr2": true })} </header> `;
}, "/home/runner/work/meme-wall/meme-wall/src/components/Header.astro", void 0);

const $$Loader = createComponent(($$result, $$props, $$slots) => {
  return renderTemplate`${maybeRenderHead()}<div class="loader" data-astro-cid-4qws3apc> <div data-astro-cid-4qws3apc></div> <div data-astro-cid-4qws3apc></div> <div data-astro-cid-4qws3apc></div> <div data-astro-cid-4qws3apc></div> <div data-astro-cid-4qws3apc></div> <div data-astro-cid-4qws3apc></div> <div data-astro-cid-4qws3apc></div> <div data-astro-cid-4qws3apc></div> <div data-astro-cid-4qws3apc></div> </div> `;
}, "/home/runner/work/meme-wall/meme-wall/src/components/Loader.astro", void 0);

var __freeze = Object.freeze;
var __defProp = Object.defineProperty;
var __template = (cooked, raw) => __freeze(__defProp(cooked, "raw", { value: __freeze(cooked.slice()) }));
var _a;
const $$Index = createComponent(($$result, $$props, $$slots) => {
  const title = "SUCHO Meme Wall";
  const description = "Collected memes from the SUCHO project concerning the Russian invasion of Ukraine.";
  const glossaries = {
    contentType: contentTypeGlossary,
    people: peopleGlossary,
    templateType: templateTypeGlossary
  };
  return renderTemplate(_a || (_a = __template(['<html lang="en"> ', "", "<body> ", " ", ' <main id="meme-wall"> <div class="wall-spacer"></div> </main> <div id="popup"> <iframe></iframe> </div> <script type="application/json" id="meme-data">', "<\/script>   </body> </html>"])), renderComponent($$result, "Head", $$Head, { "title": title, "description": description }), maybeRenderHead(), renderComponent($$result, "Header", $$Header, {}), renderComponent($$result, "Loader", $$Loader, {}), unescapeHTML(JSON.stringify({ memes, glossaries })));
}, "/home/runner/work/meme-wall/meme-wall/src/pages/index.astro", void 0);

const $$file = "/home/runner/work/meme-wall/meme-wall/src/pages/index.astro";
const $$url = "";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	default: $$Index,
	file: $$file,
	url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
